name: Build M32 Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04 # Older version of Ubuntu for better compatibility
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential flex git-core libssl-dev libncurses-dev gcc-9-aarch64-linux-gnu

      - name: Compile Kernel
        run: |
          export ARCH=arm64
          # Use GCC 9 specifically
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CC=aarch64-linux-gnu-gcc-9
          
          # Fix the "Illegal option" errors by forcing a standard shell
          export SHELL=/bin/bash
          
          # 1. Clean up
          make clean
          make mrproper
          
          # 2. Setup Config
          make m32_defconfig
          
          # 3. Neutralize the missing kperfmon files so they don't stop the build
          sed -i 's/CONFIG_KPERFMON=y/CONFIG_KPERFMON=n/g' .config
          
          # 4. Bake it!
          make -j$(nproc)
          
      - name: Upload Finished Kernel
        uses: actions/upload-artifact@v4
        with:
          name: M32-Kernel-Output
          path: arch/arm64/boot/Image.gz-dtb
